version: '3'

tasks:
  tidy:
    desc: Update all dependencies
    cmds:
      - go work sync
      - cd shared && go mod tidy
      - cd backend && go mod tidy
      - cd bot-telegram && go mod tidy

  bot:
    desc: Build Telegram bot
    cmds:
      - cd bot-telegram && go build -o ../bin/bot.exe ./cmd/bot

  backend:
    desc: Build Backend
    cmds:
      - cd backend && go build -o ../bin/backend.exe ./cmd/api

  desktop:
    desc: Build Desktop app
    cmds:
      - cd frontend-desktop && go build -o ../bin/desktop.exe

  run-bot:
    desc: Run Telegram bot
    cmds:
      - cd bot-telegram && go run ./cmd/main.go

  run-back:
    desc: Run Backend
    cmds:
      - cd backend && go run ./cmd/main.go

  all:
    desc: Build everything
    cmds:
      - task: backend
      - task: bot
      - task: desktop

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  ws:
    desc: opens workspace
    vars:
      n: '{{.n | default "default"}}'
    cmds:
      - powershell -Command "Copy-Item -Path .vscode\{{.n}}.json -Destination .vscode\settings.json -Force"

  ws-create:
    desc: creates workspace
    vars:
      n: '{{.n}}'
    cmds:
      - powershell -Command "Copy-Item -Path .vscode\default.json  -Destination .vscode\{{.n}}.json"

  ws-save:
    desc: saves current workspace to specified workspace
    vars:
      n: '{{.n}}'  
    cmds:
      - powershell -Command "Copy-Item -Path .vscode\settings.json -Destination .vscode\{{.n}}.json"

  ws-delete:
    desc: "deletes specified workspace file"
    vars:
      n: '{{.n}}'
    cmds:
      - powershell -Command "if ('{{.n}}' -ne 'default' -and '{{.n}}' -ne 'settings') { Remove-Item '.vscode\{{.n}}.json' -ErrorAction SilentlyContinue }"
  
  ws-list:
    desc: prints all saves workspaces
    cmds:
      - powershell -command "Get-ChildItem -Path .vscode | Format-Table Name, Length, LastWriteTime -AutoSize"

  ws-rename:
    desc: "renames workspace file"
    vars:
      old: '{{.s}}'
      new: '{{.d}}'
    cmds:
            - powershell -Command "if ('{{.s}}' -ne 'default' -and '{{.s}}' -ne 'settings') { Move-Item '.vscode\{{.s}}.json' '.vscode\{{.d}}.json' -ErrorAction SilentlyContinue -Force }"