package types

import (
	"context"
	"fmt"
	"strings"
	"sync/atomic"
	"unicode/utf8"
)

// - autoname() returns autogenerated name for
// NewMiddleware() if it wasn't provided.
//
// - t is used for name prefix (different for each type, see consts)
//
// Panics if t is not one of the specified ones.
//
// # Related:
//
//	//Uses:
//	const typeMiddleware string
//	const typeHandler string
//	const typeHandlerGroup string
//
//	var counterMiddleware uint64
//	var counterHandler uint64
//	var counterHandlerGroup uint64
//
//	//Used in:
//	func NewMiddleware()
//	func NewHandler()
func autoname(t string) string {
	var p *uint64
	switch t {
	case typeMiddleware:
		p = &counterMiddleware
	case typeHandler:
		p = &counterHandler
	case typeHandlerGroup:
		p = &counterHandlerGroup
	default:
		panic("autoname(t string): wrong t value")
	}
	n := atomic.AddUint64(p, 1)
	s := fmt.Sprintf("%s%d", t, n)
	return s
}

// - name prefix for Middlewares' autonames
//
// intended for autoname() only
//
// # Related:
//
//	//Used in:
//	func autoname()
const typeMiddleware = "M"

// - name prefix for Handlers' autonames
//
// intended for autoname() only
//
// # Related:
//
//	//Used in:
//	func autoname()
const typeHandler = "H"

// - name prefix for Middlewares' autonames
//
// intended for autoname() only
//
// # Related:
//
//	//Used in:
//	func autoname()
const typeHandlerGroup = "G"

// - counter for Middlewares' autonames
//
// intended for autoname() only
//
// # Related:
//
//	//Used in:
//	func autoname()
var counterMiddleware uint64

// - counter for Handlers' autonames
//
// intended for autoname() only
//
// # Related:
//
//	//Used in:
//	func autoname()
var counterHandler uint64

// - counter for HandlerGroups' autonames
//
// intended for autoname() only
//
// # Related:
//
//	//Used in:
//	func autoname()
var counterHandlerGroup uint64

func padLeft(s string, length int) string {
	slen := utf8.RuneCountInString(s)
	if slen > length {
		length = slen
	}
	pad := strings.Repeat(" ", length-slen)
	return fmt.Sprintf("%s%s", pad, s)
}
func padRight(s string, length int) string {
	slen := utf8.RuneCountInString(s)
	if slen > length {
		length = slen
	}
	pad := strings.Repeat(" ", length-slen)
	return fmt.Sprintf("%s%s", s, pad)
}

func appendPath(ctx context.Context, path string) context.Context {
	oldPath := ctx.Value(ContextKey_Path).(string)
	newPath := fmt.Sprintf("%s/%s", oldPath, path)
	return context.WithValue(ctx, ContextKey_Path, newPath)
}
