version: '3'

tasks:
  bot:
    desc: Build Telegram bot
    cmds:
      - cd ../frontend-bot && go build -o ../bin/bot.exe ./cmd/bot

  backend:
    desc: Build Backend
    cmds:
      - cd ../backend && go build -o ../bin/backend.exe ./cmd/api

  desktop:
    desc: Build Desktop app
    cmds:
      - cd ../frontend-desktop && go build -o ../bin/desktop.exe

  run-bot:
    desc: Run Telegram bot
    cmds:
      - cd ../frontend-bot && go run ./cmd/main.go

  run-backend:
    desc: Run Backend
    cmds:
      - cd ../backend && go run ./cmd/api/main.go

  all:
    desc: Build everything
    cmds:
      - task: backend
      - task: bot
      - task: desktop

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin

  tidy:
    desc: Format code
    cmds:
      - cd ../shared && go mod tidy && go mod download
      - cd ../backend && go mod tidy && go mod download
      - cd ../frontend-bot && go mod tidy && go mod download

  test:
    desc: Run all tests
    cmds:
      - go test ./...